name: Hello World
'on': push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: 'echo "Hello, world!"'
      - name: Echo text1
        run: 'echo "Hello, worldnew!"'
